# tutorial.conf

# Połączenie do bazy (format: postgres://user:pass@host:port/dbname)
# Upewnij się, że "postgres" na końcu to nazwa Twojej bazy danych
db-uri = "postgres://authenticator:zaq12wsx@localhost:5432/szatnia"

# Schemat, który chcesz wystawić jako API
db-schema = "api"

# Rola anonimowa (używana, gdy klient nie jest zalogowany)
# WAŻNE: Musisz mieć tę rolę stworzoną w bazie (np. web_anon lub anon)
db-anon-role = "web_anon"
jwt-secret = "to_jest_moj_sekretny_klucz_do_testow_min_32_znaki"
